# Site settings
title: Plantas Ornamentales
description: Decoración del jadín, hogar u oficina con plantas 
keywords: plantas ornamentales, jardín, hogar
author: Yass
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
